# Generated by Django 5.1 on 2024-10-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloPeliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='tipo',
            field=models.CharField(choices=[('pelicula', 'Película'), ('serie', 'Serie')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.URLField(),
        ),
    ]
