# Generated by Django 5.1 on 2024-10-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloPeliculas', '0002_pelicula_tipo_alter_pelicula_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='fecha_exhibicion',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='hora_exhibicion',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='valor_ticket',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='tipo',
            field=models.CharField(choices=[('pelicula', 'Película'), ('serie', 'Serie')], help_text='Pelicula o Serie', max_length=50),
        ),
    ]
