# Generated by Django 5.1 on 2024-10-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloPeliculas', '0003_remove_pelicula_fecha_exhibicion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la serie', max_length=50)),
                ('genero', models.CharField(choices=[('Accion', 'Acción'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Suspenso', 'Suspenso'), ('Crimen', 'Crimen'), ('Romance', 'Romance'), ('Terror', 'Terror'), ('Musical', 'Musical'), ('Aventura', 'Aventura'), ('Animacion', 'Animacion'), ('Ciencia ficcion', 'Ciencia ficción'), ('Documental', 'Documental'), ('Animacion', 'Animación')], help_text='Género de la serie', max_length=20)),
                ('clasificacion', models.CharField(choices=[('TE', 'TE'), ('TE+7', 'TE+7'), ('14+', '14+'), ('18+', '18+')], help_text='Clasificación de la serie', max_length=8)),
                ('año', models.PositiveIntegerField(help_text='Año de publicacion')),
                ('temporadas', models.PositiveIntegerField(help_text='Número de temporadas')),
                ('capitulos', models.PositiveIntegerField(help_text='Número de capítulos por temporada')),
                ('resena', models.TextField(blank=True, help_text='Breve reseña del contenido de la serie')),
                ('imagen', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='año',
            field=models.PositiveIntegerField(default=1, help_text='Año de publicacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.PositiveIntegerField(help_text='Duración de la película en minutos'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('Accion', 'Acción'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Suspenso', 'Suspenso'), ('Crimen', 'Crimen'), ('Romance', 'Romance'), ('Terror', 'Terror'), ('Musical', 'Musical'), ('Aventura', 'Aventura'), ('Animacion', 'Animacion'), ('Ciencia ficcion', 'Ciencia ficción'), ('Documental', 'Documental'), ('Animacion', 'Animación')], help_text='Género de la película', max_length=20),
        ),
    ]
