# Generated by Django 5.1 on 2024-11-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloPeliculas', '0005_pelicula_imagenbanner_serie_imagenbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagenname',
            field=models.URLField(blank=True, help_text='URL del nombre del archivo de la imagen'),
        ),
        migrations.AddField(
            model_name='serie',
            name='imagenname',
            field=models.URLField(blank=True, help_text='URL del nombre del archivo de la imagen'),
        ),
    ]
