# Generated by Django 5.1 on 2024-11-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloPeliculas', '0006_pelicula_imagenname_serie_imagenname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.URLField(help_text='URL de la imagen de la película'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='imagen',
            field=models.URLField(help_text='URL de la imagen de la serie'),
        ),
    ]
